"""
Standardized Reason Codes for the Smart Routing Engine
AI-Driven Intelligent Greywater Management and Smart Reuse Routing System

Defines machine-readable diagnostic and audit codes emitted by the routing engine.
Every routing decision must carry at least one reason code.
"""

# Water-Quality and Safety Codes
WQ_CRITICAL = "WQ_CRITICAL"
WQ_HIGH_TURBIDITY = "WQ_HIGH_TURBIDITY"
WQ_HIGH_BOD = "WQ_HIGH_BOD"
WQ_HIGH_COD = "WQ_HIGH_COD"
WQ_HIGH_TSS = "WQ_HIGH_TSS"
WQ_HIGH_ECOLI = "WQ_HIGH_ECOLI"
WQ_EXTREME_PH = "WQ_EXTREME_PH"
WQ_HIGH_SALINITY = "WQ_HIGH_SALINITY"
WQ_HIGH_TDS = "WQ_HIGH_TDS"
WQ_SEPTIC_RISK = "WQ_SEPTIC_RISK"
WQ_ACCEPTABLE = "WQ_ACCEPTABLE"

# Anomaly Detection Codes
ANOMALY_DETECTED = "ANOMALY_DETECTED"
ANOMALY_SAFETY_OVERRIDE = "ANOMALY_SAFETY_OVERRIDE"
ANOMALY_REVIEW = "ANOMALY_REVIEW"
ANOMALY_CLEAN = "ANOMALY_CLEAN"

# Weather & Environmental Context Codes
WEATHER_FAVORABLE = "WEATHER_FAVORABLE"
WEATHER_UNFAVORABLE = "WEATHER_UNFAVORABLE"
HIGH_RAINFALL = "HIGH_RAINFALL"
HIGH_PRECIP_PROBABILITY = "HIGH_PRECIP_PROBABILITY"
FREEZING_TEMPERATURE = "FREEZING_TEMPERATURE"
IRRIGATION_DEFERRED = "IRRIGATION_DEFERRED"
INDOOR_DECOUPLED = "INDOOR_DECOUPLED"
WEATHER_UNAVAILABLE = "WEATHER_UNAVAILABLE"

# Storage & Deterioration Codes
STORAGE_NORMAL = "STORAGE_NORMAL"
STORAGE_AGING = "STORAGE_AGING"
STORAGE_HIGH_DETERIORATION = "STORAGE_HIGH_DETERIORATION"
STAGNATION_DETECTED = "STAGNATION_DETECTED"
STORAGE_REVIEW = "STORAGE_REVIEW"
STORAGE_UNAVAILABLE = "STORAGE_UNAVAILABLE"

# Model Confidence Codes
MODEL_HIGH_CONFIDENCE = "MODEL_HIGH_CONFIDENCE"
MODEL_MEDIUM_CONFIDENCE = "MODEL_MEDIUM_CONFIDENCE"
MODEL_LOW_CONFIDENCE = "MODEL_LOW_CONFIDENCE"
MODEL_UNAVAILABLE = "MODEL_UNAVAILABLE"

# Route Assignment Codes
ROUTE_SEWER = "ROUTE_SEWER"
ROUTE_BIOFILTRATION = "ROUTE_BIOFILTRATION"
ROUTE_IRRIGATION = "ROUTE_IRRIGATION"
ROUTE_INDOOR_REUSE = "ROUTE_INDOOR_REUSE"

# Override Codes
OVERRIDE_SAFETY_CRITICAL = "OVERRIDE_SAFETY_CRITICAL"
OVERRIDE_ANOMALY_HAZARD = "OVERRIDE_ANOMALY_HAZARD"
OVERRIDE_STORAGE_DETERIORATION = "OVERRIDE_STORAGE_DETERIORATION"
OVERRIDE_LOW_CONFIDENCE = "OVERRIDE_LOW_CONFIDENCE"
OVERRIDE_NONE = "OVERRIDE_NONE"
